### ISSUE TITLE
Exception has occurred. MissingPluginException (MissingPluginException(No implementation found for method run on channel com.pichillilorenzo/flutter_headless_inappwebview))

### ISSUE THREAD

**Issue by Nubdubi** [ashishpipaliya/extractor#1]
what can i fix this error?

Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method run on channel com.pichillilorenzo/flutter_headless_inappwebview))

**Comment by ashishpipaliya** [comment]
- stop currently running app
- `flutter pub get`
- run app
